Modify build workflow for permissions and logging
Updated the GitHub Actions workflow to set permissions for contents and changed the log file path for error logging. Also upgraded the git-auto-commit-action version from v4 to v5.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,6 +24,8 @@ jobs:
   build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
+    permissions: 
+      contents: write
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -53,10 +55,10 @@ jobs:
       - name: Show Build Log on Failure
         run: |
           echo "--- Error Log Contents ---"
-          cat /home/runner/work/Coe-Catalog-2023-2024/Coe-Catalog-2023-2024/index.log || echo "Build log not found or empty."
+          cat /home/runner/work/Coe-Catalog-2026-2027/Coe-Catalog-2026-2027/index.log || echo "Build log not found or empty."
           
       # Push changes back to the repo
       - name: Push changes
-        uses: stefanzweifel/git-auto-commit-action@v4
+        uses: stefanzweifel/git-auto-commit-action@v5
         with:
           commit_message: Updated ouput files
